default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails_dev
  password: "railsdev123"

development:
  <<: *default
  database: comic_book_development

test:
  <<: *default
  database: comic_book_test

production:
  <<: *default
  database: comic_book_production
